spring:
  datasource:
    url: jdbc:mysql://localhost:3306/[Database 스키마]
    username: [ DB 아이디 ]
    password: [ DB 비밀번호 ]
    driver-class-name: [ JDBC 드라이버 ]
  security:
    oauth2:
      resourceserver:

app:
  jwt:
    secretKey: 135b8378904571a649516713c9b3bbffc14f3464a3131504aec324cde5327b4d